replicaCount: 1

image:
  repository: "${DOCKER_HUB_USERNAME}/order-service"
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  nodePort: 30001

containerPort: 8004

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
